/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreatmentsSlugRouteImport } from './routes/treatments.$slug'
import { Route as ApiPublicRefundRequestRouteImport } from './routes/api/public/refund-request'
import { Route as ApiPublicQuizLeadRouteImport } from './routes/api/public/quiz-lead'
import { Route as ApiPublicLeadMagnetRouteImport } from './routes/api/public/lead-magnet'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'
import { Route as ApiPublicBookingRouteImport } from './routes/api/public/booking'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsSlugRoute = TreatmentsSlugRouteImport.update({
  id: '/treatments/$slug',
  path: '/treatments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefundRequestRoute = ApiPublicRefundRequestRouteImport.update({
  id: '/api/public/refund-request',
  path: '/api/public/refund-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuizLeadRoute = ApiPublicQuizLeadRouteImport.update({
  id: '/api/public/quiz-lead',
  path: '/api/public/quiz-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadMagnetRoute = ApiPublicLeadMagnetRouteImport.update({
  id: '/api/public/lead-magnet',
  path: '/api/public/lead-magnet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingRoute = ApiPublicBookingRouteImport.update({
  id: '/api/public/booking',
  path: '/api/public/booking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/quiz': typeof QuizRoute
  '/refund': typeof RefundRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/api/public/booking': typeof ApiPublicBookingRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/lead-magnet': typeof ApiPublicLeadMagnetRoute
  '/api/public/quiz-lead': typeof ApiPublicQuizLeadRoute
  '/api/public/refund-request': typeof ApiPublicRefundRequestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/quiz': typeof QuizRoute
  '/refund': typeof RefundRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/api/public/booking': typeof ApiPublicBookingRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/lead-magnet': typeof ApiPublicLeadMagnetRoute
  '/api/public/quiz-lead': typeof ApiPublicQuizLeadRoute
  '/api/public/refund-request': typeof ApiPublicRefundRequestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/quiz': typeof QuizRoute
  '/refund': typeof RefundRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/api/public/booking': typeof ApiPublicBookingRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/lead-magnet': typeof ApiPublicLeadMagnetRoute
  '/api/public/quiz-lead': typeof ApiPublicQuizLeadRoute
  '/api/public/refund-request': typeof ApiPublicRefundRequestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/approach'
    | '/chat'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/programs'
    | '/quiz'
    | '/refund'
    | '/services'
    | '/terms'
    | '/treatments/$slug'
    | '/api/public/booking'
    | '/api/public/chat'
    | '/api/public/lead-magnet'
    | '/api/public/quiz-lead'
    | '/api/public/refund-request'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/approach'
    | '/chat'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/programs'
    | '/quiz'
    | '/refund'
    | '/services'
    | '/terms'
    | '/treatments/$slug'
    | '/api/public/booking'
    | '/api/public/chat'
    | '/api/public/lead-magnet'
    | '/api/public/quiz-lead'
    | '/api/public/refund-request'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/approach'
    | '/chat'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/programs'
    | '/quiz'
    | '/refund'
    | '/services'
    | '/terms'
    | '/treatments/$slug'
    | '/api/public/booking'
    | '/api/public/chat'
    | '/api/public/lead-magnet'
    | '/api/public/quiz-lead'
    | '/api/public/refund-request'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApproachRoute: typeof ApproachRoute
  ChatRoute: typeof ChatRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRoute
  QuizRoute: typeof QuizRoute
  RefundRoute: typeof RefundRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  TreatmentsSlugRoute: typeof TreatmentsSlugRoute
  ApiPublicBookingRoute: typeof ApiPublicBookingRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicLeadMagnetRoute: typeof ApiPublicLeadMagnetRoute
  ApiPublicQuizLeadRoute: typeof ApiPublicQuizLeadRoute
  ApiPublicRefundRequestRoute: typeof ApiPublicRefundRequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/$slug': {
      id: '/treatments/$slug'
      path: '/treatments/$slug'
      fullPath: '/treatments/$slug'
      preLoaderRoute: typeof TreatmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refund-request': {
      id: '/api/public/refund-request'
      path: '/api/public/refund-request'
      fullPath: '/api/public/refund-request'
      preLoaderRoute: typeof ApiPublicRefundRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/quiz-lead': {
      id: '/api/public/quiz-lead'
      path: '/api/public/quiz-lead'
      fullPath: '/api/public/quiz-lead'
      preLoaderRoute: typeof ApiPublicQuizLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead-magnet': {
      id: '/api/public/lead-magnet'
      path: '/api/public/lead-magnet'
      fullPath: '/api/public/lead-magnet'
      preLoaderRoute: typeof ApiPublicLeadMagnetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking': {
      id: '/api/public/booking'
      path: '/api/public/booking'
      fullPath: '/api/public/booking'
      preLoaderRoute: typeof ApiPublicBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApproachRoute: ApproachRoute,
  ChatRoute: ChatRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRoute,
  QuizRoute: QuizRoute,
  RefundRoute: RefundRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  TreatmentsSlugRoute: TreatmentsSlugRoute,
  ApiPublicBookingRoute: ApiPublicBookingRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicLeadMagnetRoute: ApiPublicLeadMagnetRoute,
  ApiPublicQuizLeadRoute: ApiPublicQuizLeadRoute,
  ApiPublicRefundRequestRoute: ApiPublicRefundRequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
